FROM php:7.3-fpm-alpine

# Install Composer
RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer

# Update Timezone
RUN apk add --update tzdata && \
    cp /usr/share/zoneinfo/Asia/Bangkok /etc/localtime && \
    apk del tzdata

# Install Additional dependencies
RUN apk update && apk add --no-cache \
    build-base shadow vim curl \
    freetype-dev \
    libjpeg-turbo-dev \
    libwebp-dev \
    libpng-dev \
    openssh \
    git \
    npm \
    php7 \
    imap-dev \
    openssl-dev \
    php7-fpm \
    php7-common \
    php7-pdo \
    php7-pdo_mysql \
    php7-mysqli \
    php7-mcrypt \
    php7-mbstring \
    php7-xml \
    php7-openssl \
    php7-json \
    php7-phar \
    php7-zip \
    php7-gd \
    php7-dom \
    php7-session \
    php7-zlib

RUN docker-php-ext-install pdo pdo_mysql \
    && docker-php-ext-enable pdo_mysql \
    && docker-php-ext-install mysqli \
    && docker-php-ext-enable mysqli \
    && docker-php-ext-configure imap --with-imap --with-imap-ssl \
    && docker-php-ext-install imap

RUN docker-php-ext-configure gd \
    --with-gd \
    --with-webp-dir \
    --with-jpeg-dir \
    --with-png-dir \
    --with-zlib-dir \
    --with-freetype-dir

RUN docker-php-ext-install gd

# Clean APK cache
RUN rm -rf /var/cache/apk/*

COPY ./config/php/php.ini /usr/local/etc/php/conf.d/php.ini
COPY ./web/ /var/www/web
RUN chmod -R 777 /var/www/web/public/upload
WORKDIR /var/www/web

EXPOSE 9000
